version: '3'

services:
  # Laravel application - Environment vars precede .env file
  docker_laravel_app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: docker_laravel_app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
      - ./docker/app.conf:/etc/apache2/sites-enabled/000-default.conf
    environment:
      DB_CONNECTION: mysql
      DB_HOST: docker_laravel_db
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: laravel_db
      DB_PASSWORD: laravel_db
    ports:
      - 8000:80
    networks:
      - docker_laravel_network

  # Database - Uses port 3306
  docker_laravel_db:
    image: mysql:8.0
    container_name: docker_laravel_db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_db
      MYSQL_PASSWORD: laravel_db
    volumes:
      - docker_laravel_db_data:/var/lib/mysql/
    networks:
      - docker_laravel_network

networks:
  docker_laravel_network:
    driver: bridge

volumes:
  docker_laravel_db_data:
    driver: local
